#!/usr/bin/env bash
# Script to show a message infinitely and other when sigterm ocurred
_term()
{
  echo 'I am invincible!!!'
}

trap _term SIGTERM

while "true"
do
  echo 'To infinity and beyond'
  sleep 2
done
